### list aluno
GET http://localhost:3000/aluno

### get aluno
GET http://localhost:3000/aluno/

### create aluno
POST http://localhost:3000/aluno
Content-Type: application/json

{
    "cpf": "111111111111",
    "nome": "Osvaldo Pereira Silva",
    "telefone": "77912341234",
    "nascimento": "2000-09-12",
    "enderecoResidencia": "casa da mãe joana",
    "enderecoEscola": "bairro ao lado",
    "turnoEstudo": "Noturno",
    "email": "111111111111@ifba.edu.br",
    "codigoTurma": "1234"
}

### update aluno
PATCH http://localhost:3000/aluno/aln_qS5uOacDrnd8Qik1IWOJX
Content-Type: application/json

{
    "cpf": "87789987",
    "nome": "Osvaldo Pereira Silva",
    "telefone": "77900000000",
    "nascimento": "2000-10-10",
    "enderecoResidencia": "casa da mãe joana",
    "enderecoEscola": "bairro ao lado",
    "turnoEstudo": "Noturno",
    "email": "1234@ifba.edu.br",
    "codigoTurma": "1234"
}


### delete aluno
DELETE http://localhost:3000/aluno/aln_bHLFqlWPGf809KdTfaM37